// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFgY8lhhx-JqWVgGOBiJPP_-a6-xx3HZc',
    appId: '1:428549779999:web:ca42b6f909b76199865b2a',
    messagingSenderId: '428549779999',
    projectId: 'driverapp-3845f',
    authDomain: 'driverapp-3845f.firebaseapp.com',
    storageBucket: 'driverapp-3845f.firebasestorage.app',
    measurementId: 'G-QES3CC4NXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQsvK_dkvkpbCma4r9u-8VSFI2DvN2gZ0',
    appId: '1:428549779999:android:de9d7cc3c630d364865b2a',
    messagingSenderId: '428549779999',
    projectId: 'driverapp-3845f',
    storageBucket: 'driverapp-3845f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEhiDiDZzq0aeIi_so9G5pPTc1ruGrVI',
    appId: '1:428549779999:ios:b257ba312ab540a0865b2a',
    messagingSenderId: '428549779999',
    projectId: 'driverapp-3845f',
    storageBucket: 'driverapp-3845f.firebasestorage.app',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEhiDiDZzq0aeIi_so9G5pPTc1ruGrVI',
    appId: '1:428549779999:ios:b257ba312ab540a0865b2a',
    messagingSenderId: '428549779999',
    projectId: 'driverapp-3845f',
    storageBucket: 'driverapp-3845f.firebasestorage.app',
    iosBundleId: 'com.example.driverapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFgY8lhhx-JqWVgGOBiJPP_-a6-xx3HZc',
    appId: '1:428549779999:web:d1d83d9cb8593342865b2a',
    messagingSenderId: '428549779999',
    projectId: 'driverapp-3845f',
    authDomain: 'driverapp-3845f.firebaseapp.com',
    storageBucket: 'driverapp-3845f.firebasestorage.app',
    measurementId: 'G-5H3TDWDY19',
  );
}
