import 'package:driverapp/models/order.dart';

class MockData {
  static List<Order> getMockOrders() {
    return [
      Order(
        orderId: 'DH001',
        customerName: 'Công ty TNHH Logistics Việt Nam',
        creator: 'Nguyễn Văn A',
        deliveryDate: '15/05/2023',
        deliveryLocation: 'Cảng Cát Lái, TP.HCM',
        status: 'Đang giao',
        shippingCode: 'VN123456789',
        containerType: '40 feet lạnh',
        containerTemperature: -18.5,
        orderWeight: 15000,
        pickupDate: '13/05/2023',
        pickupLocation: 'KCN Tân Thuận, Quận 7, TP.HCM',
        containerReturnLocation: 'Depot Tân Cảng, TP.HCM',
        transportationType: 'Xuất',
        containerId: 'ABCD1234567',
        partnerName: 'Công ty ABC International',
        partnerPhone: '0901234567',
        isPaid: true,
      ),
      Order(
        orderId: 'DH002',
        customerName: 'Công ty CP Thương mại Toàn Cầu',
        creator: 'Trần Thị B',
        deliveryDate: '20/05/2023',
        deliveryLocation: 'Cảng Hải Phòng',
        status: 'Chờ xử lý',
        shippingCode: 'VN987654321',
        containerType: '20 feet thường',
        containerTemperature: null,
        orderWeight: 8500,
        pickupDate: '18/05/2023',
        pickupLocation: 'KCN Đình Vũ, Hải Phòng',
        containerReturnLocation: 'Depot Hải Phòng',
        transportationType: 'Nhập',
        containerId: 'EFGH7654321',
        partnerName: 'Công ty XYZ Logistics',
        partnerPhone: '0912345678',
        isPaid: false,
      ),
      Order(
        orderId: 'DH003',
        customerName: 'Công ty TNHH Xuất Nhập Khẩu Đông Á',
        creator: 'Lê Văn C',
        deliveryDate: '25/05/2023',
        deliveryLocation: 'ICD Sóng Thần, Bình Dương',
        status: 'Đã giao',
        shippingCode: 'VN456789123',
        containerType: '45 feet cao',
        containerTemperature: null,
        orderWeight: 22000,
        pickupDate: '22/05/2023',
        pickupLocation: 'KCN VSIP 1, Bình Dương',
        containerReturnLocation: 'Depot Bình Dương',
        transportationType: 'Xuất',
        containerId: 'IJKL9876543',
        partnerName: 'Công ty DEF International',
        partnerPhone: '0987654321',
        isPaid: true,
      ),
      Order(
        orderId: 'DH004',
        customerName: 'Công ty TNHH Thực phẩm Đông lạnh Việt',
        creator: 'Phạm Thị D',
        deliveryDate: '30/05/2023',
        deliveryLocation: 'Kho lạnh An Phú, Quận 2, TP.HCM',
        status: 'Đang giao',
        shippingCode: 'VN789123456',
        containerType: '40 feet lạnh',
        containerTemperature: -20.0,
        orderWeight: 17500,
        pickupDate: '28/05/2023',
        pickupLocation: 'Cảng Cát Lái, TP.HCM',
        containerReturnLocation: 'Depot Tân Cảng, TP.HCM',
        transportationType: 'Nhập',
        containerId: 'MNOP5432167',
        partnerName: 'Công ty GHI Seafood',
        partnerPhone: '0978123456',
        isPaid: false,
      ),
      Order(
        orderId: 'DH005',
        customerName: 'Công ty CP May Mặc Quốc tế',
        creator: 'Hoàng Văn E',
        deliveryDate: '05/06/2023',
        deliveryLocation: 'KCN Tây Bắc, Củ Chi, TP.HCM',
        status: 'Chờ xử lý',
        shippingCode: 'VN321654987',
        containerType: '40 feet thường',
        containerTemperature: null,
        orderWeight: 12000,
        pickupDate: '03/06/2023',
        pickupLocation: 'Cảng Hiệp Phước, TP.HCM',
        containerReturnLocation: 'Depot Hiệp Phước, TP.HCM',
        transportationType: 'Nhập',
        containerId: 'QRST1234987',
        partnerName: 'Công ty JKL Fashion',
        partnerPhone: '0909876543',
        isPaid: true,
      ),
    ];
  }
}
